### ISSUE TITLE
Buffer lag (?)

### ISSUE THREAD

**Issue by cyberhuman** [zorxx/neopixel#1]
Hello.
Thank you very much for the library! I tried to use it in a new project but I stumbled upon an issue.
The following code is supposed to set the pixel to the red color, then to green, then turn it off. But the last command is not executed. I played around with the code and figured out when calling `neopixel_SetPixel`, the command is sent out only on the next `neopixel_SetPixel` invocation. I looked through the source code and didn't manage to figure it out.
Any ideas what can be wrong?
 
```c
void app_main(void)
{
  tNeopixelContext ctx = neopixel_Init(1, GPIO_NUM_7);
  tNeopixel pixel[] = {
    { 0, NP_RGB(50, 0, 0) },
    { 0, NP_RGB(0, 50, 0) },
    { 0, NP_RGB(0, 0, 0) },
  };
  neopixel_SetPixel(ctx, &pixel[0], 1); 
  vTaskDelay(pdMS_TO_TICKS(1000));
  neopixel_SetPixel(ctx, &pixel[1], 1); 
  vTaskDelay(pdMS_TO_TICKS(1000));
  neopixel_SetPixel(ctx, &pixel[2], 1); 
  vTaskDelay(portMAX_DELAY);
}
```
The controller is ESP32-C3.

**Comment by zorxx** [comment]
Thank you for the concise bug report. A fix to this has been pushed and a new version of ESP-IDF component as been published (1.0.3)

**Comment by cyberhuman** [comment]
Horray! Thank you.

**Comment by cyberhuman** [comment]
Hi, just a heads-up! I was trying to figure out an issue in my code and since it affected the LED, I was re-checking the library's code, too, and suddenly realized what the real issue with the library is.
It turns out `i2s_channel_write` will return when it finishes copying data to the DMA buffer. The code then calls `i2s_channel_disable`, which may or may not cancel the ongoing transfer! I looked around and unfortunately it seems ESP-IDF doesn't provide a clean way to disable the I2S channel as soon as the transfer is complete. I hacked a solution that involves the `on_sent` callback registration (via `i2s_channel_register_event_callback`), and waiting for a signal from the callback as soon as the total "sent" buffer size exceeds the number of bytes written (note the callback receives the size of the DMA buffer just sent and not the size of the actual data 😞). It works without re-sending the buffer the second time! Here are some excerpts:
```c
   uint32_t bytesWritten;
   SemaphoreHandle_t dataSent;
}  tNpContext;
```
```c
static IRAM_ATTR bool i2s_tx_queue_sent_callback(i2s_chan_handle_t handle, i2s_event_data_t *event, void *user_ctx)
{
   tNpContext *c = (tNpContext*)user_ctx;
   if ((c->bytesWritten += event->size) >= c->bufferSize) {
      xSemaphoreGive(c->dataSent);
   }
   return false;
}
```
```c
   c->bytesWritten = 0;
   c->dataSent = xSemaphoreCreateBinary();
   i2s_event_callbacks_t callbacks = {
       .on_recv = NULL,
       .on_recv_q_ovf = NULL,
       .on_sent = i2s_tx_queue_sent_callback,
       .on_send_q_ovf = NULL,
   };
   i2s_channel_register_event_callback(c->i2s, &callbacks, c);
```
```
         c->bytesWritten = 0;
         size_t bytes_loaded;
         i2s_channel_preload_data(c->i2s, buffer, c->bufferSize, &bytes_loaded);
         i2s_channel_enable(c->i2s);
         if (bytes_loaded < c->bufferSize) {
           i2s_channel_write(c->i2s, buffer + bytes_loaded, c->bufferSize - bytes_loaded, NULL, I2S_TIMEOUT_TICKS);
         }
         xSemaphoreTake(c->dataSent, portMAX_DELAY);
         i2s_channel_disable(c->i2s);
```
Hope this helps.

**Comment by zorxx** [comment]
Excellent - thank you for the high-quality work. I've incorporated these changed into the master branch
