### ISSUE TITLE
First LED randomly turns green with full brightness

### ISSUE THREAD

**Issue by efogdev** [zorxx/neopixel#2]
Hey, thank you for this amazing component!

I have a "little" problem and I'm not sure if it is a software issue.
So, I've a PCB with 13 [WS2812B](https://datasheet.lcsc.com/lcsc/2301111010_XINGLIGHT-XL-1010RGBC-WS2812B_C5349953.pdf) LEDs. 

And here is my code (basically, just turn off everything):
```
static void led_task(void* arg)
{
    tNeopixelContext neopixel = neopixel_Init(PIXEL_COUNT, GPIO_WS2812B);

    for (;;) {
        uint8_t i = 0;
        tNeopixel pixel[] =
            {
                { i++, NP_RGB(0, 0, 0) }, // not copying everything here; 13 identical lines for now lmao
            };

        neopixel_SetPixel(neopixel, pixel, ARRAY_SIZE(pixel));
        vTaskDelay(pdMS_TO_TICKS(16));
    }
}
```

From my observations, each time I use `neopixel_SetPixel`, there is some (idk if random) probability that the first LED green value will end up with full brightness. Other LEDs are unaffected. Other colors of the 1st LED are unaffected. 

I'm facing this issue with my 2nd circuit boards batch; for the 1st batch I thought that my problem was noise so I have added 510 Ohm resistor between the esp32-s3 pin and the 1st LED input. However, I still experience the problem.

I've tried to dig into the source code, but no luck so far due to lack of experience and equipment.
Also: sometimes that just doesn't happen at all and everything works as expected. Then I reconnect it to the power supply and it glitches again. A bypass cap is really close to the 1st LED.

**Comment by zorxx** [comment]
I've tested your code (with the pixel structure initialized with 13 elements) on a SparkFun NeoPixel Stick
(https://www.sparkfun.com/products/12661) and was not able to reproduce the behavior you report.

The best suggestion I have is to emulate a schematic similar to the one shown here:
https://learn.adafruit.com/adafruit-neopixel-uberguide/downloads

**Comment by efogdev** [comment]
@zorxx I have replaced I2S_STD_MSB_SLOT_DEFAULT_CONFIG with I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG and now it works perfectly. Maybe my LEDs are special I don't know.

**Comment by polhenarejos** [comment]
I had the same problem and @EfogDev solution worked to me.

Perhaps could it be an additional param or method to init() @zorxx for avoiding modifying the source?

**Comment by zorxx** [comment]
@polhenarejos Can you send me details about your hardware (schematic or otherwise)? I'd like to understand the difference before making the change.
