### ISSUE TITLE
ESP32-C6 `W i2s_platform: i2s controller 0 has been occupied by i2s_driver`

### ISSUE THREAD

**Issue by CircuitGuy** [zorxx/neopixel#5]
I just pulled this as a quick example and tried to adapt it to Adafruit's C6 feather board.
Set GPIO_20 high, and configured the example for pin 9.
https://learn.adafruit.com/adafruit-esp32-c6-feather/pinouts

When this component tries to create a new i2s channel, it hangs with the following warning/error.
```
W (40326) i2s_platform: i2s controller 0 has been occupied by i2s_driver
E (40326) i2s_common: i2s0 might be occupied by other component
E (40336) i2s_common: i2s_new_channel(887): get i2s object failed
E (40336) i2s_std: i2s_channel_init_std_mode(204): input parameter 'handle' is NULL
E (40346) i2s_common: i2s_channel_register_event_callback(315): input parameter 'handle' is NULL
```

I'm still looking around, but I'm pretty confused by this error. I don't see what else out of the example would have pulled that driver. It also looks like the component code is working 'correctly' and pulling an AUTO channel.

**Comment by zorxx** [comment]
This bug was elusive - the i2s channel wasn't getting closed properly when the i2s_del_channel happened just before the neopixel task was terminated. This is fixed now - thanks for the report
